spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: medium_backend_db
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 315041289771-qnn8cif3hftbdd6h72tosbkluree5dt3.apps.googleusercontent.com
            clientSecret: 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

server:
  port: 8080
